Repository Ureca-Final-Project-Team2/be_badata, pull requests merged in 2025-08, with the labels that each got.

#341 Feat: [BADA-329] 실시간 인기글 기능 개발
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/MockController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/TrendingController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/LikeService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/TrendingKeywordService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/TrendingPostService.java
Labels: ✨ Feature

#344 Feat: [BADA-319] 지도 에포크 값 수정
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/store/service/StoreService.java
Labels: ✨ Feature

#343 Feat: [BADA-335] 구매 기프티콘 확인 API 개발
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PurchaseController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetPurchaseGifticonDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetPurchaseGifticonImageResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PurchaseService.java
Labels: ✨ Feature

#348 Feat: [BADA-339] 테스트 메시지 형식 알림 변경
  src/main/java/com/TwoSeaU/BaData/domain/alarm/AlarmController.java
Labels: ✨ Feature

#351 Feat: [BADA-338] 거래 커뮤니티 고도화
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/ReportController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SavePurchaseReportRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Report.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/enums/ReportType.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/GifticonCategoryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/GifticonRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PartnerRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PaymentQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/RecommendService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ReportService.java
Labels: ✨ Feature

#355 Feat: [BADA-337] 예약 및 재입고 날짜 비즈니스 로직 변경
  src/main/java/com/TwoSeaU/BaData/BaDataApplication.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReservationScheduler.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RestockService.java
  src/test/java/com/TwoSeaU/BaData/domain/rental/service/RentalServiceTest.java
Labels: ✨ Feature

#357 Feat: [BADA-331] 신고 시 이메일 알림 + fcm 알림 적용
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/trade/event/ReportEmailEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/event/ReportFcmEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/event/ReportListenerEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ReportNotificationService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ReportService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/FcmTokenRepository.java
  src/main/java/com/TwoSeaU/BaData/global/email/EmailConfig.java
  src/main/java/com/TwoSeaU/BaData/global/email/MailService.java
  src/main/java/com/TwoSeaU/BaData/global/exception/GlobalException.java
  src/main/java/com/TwoSeaU/BaData/global/fcm/FCMService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#358 Perf: [BADA-344] 추천 시스템 고도화
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/RecommendController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetPurchaseGifticonDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostVectorizer.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/RecommendService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/UserProfileVectorizer.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/VectorUtils.java
Labels: ⚡️performance

#361 [BADA-346] 예약 및 리뷰 동시성 처리
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/Store.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreRepository.java
  src/test/java/com/TwoSeaU/BaData/domain/rental/service/RentalServiceTest.java
Labels: ✨ Feature

#366 Feat: [BADA-347] 재입고 알림 시 이메일 인증 추가
  src/main/java/com/TwoSeaU/BaData/domain/alarm/AlarmController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/event/RentalListenerEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/event/RestockEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/global/fcm/FCMService.java
Labels: ✨ Feature

#367 Feat: [BADA-350] 판매/구매 내역 응답에 MobileCarrier 추가
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetPurchaseResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetSaleResponse.java
Labels: ✨ Feature

#370 Feat: [BADA-351] 공유기 대여 시 대여 마감일, 스토어 ID 추가
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetRentalResponse.java
Labels: ✨ Feature

#365 Feat: [BADA-345] ES를 활용한 게시글 검색 구현
  .github/workflows/ci.yml
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PostDocument.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostDocumentRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostSearchService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ⚡️performance

#368 Performance: [BADA-341] SOS 알림 요청 동시성 제어
  src/main/java/com/TwoSeaU/BaData/domain/sos/entity/Sos.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/exception/SosException.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/repository/SosRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/service/SosService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
Labels: ✨ Feature

#375 Fix: [BADA-353] 중복 게시글 방지
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/RecommendController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/RecommendService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/TrendingPostService.java
Labels: 🐞 BugFix

#376 Feat: [BADA-354] SOS 한달에 한 번 사용 여부 검증
  src/main/java/com/TwoSeaU/BaData/domain/sos/exception/SosException.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/repository/SosRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/service/SosService.java
Labels: ✨ Feature

#378 Fix: [BADA-356] SSE 연결 접속 오류 해결
  src/main/java/com/TwoSeaU/BaData/domain/sos/controller/NotificationController.java
Labels: 🐞 BugFix

#382 Feat: [BADA-358] SOS 응답자에게 10코인 보상 지급
  src/main/java/com/TwoSeaU/BaData/domain/sos/entity/Sos.java
Labels: ✨ Feature

#384 Fix: [BADA-360] Cors 에러 해결
  src/main/java/com/TwoSeaU/BaData/global/config/WebConfig.java
Labels: 🐞 BugFix

#385 Fix: [BADA-360] Cors 에러 해결
  src/main/java/com/TwoSeaU/BaData/global/config/WebConfig.java
Labels: 🐞 BugFix

#389 Fix: [BADA-363] SSE 연결 오류 수정
  src/main/java/com/TwoSeaU/BaData/domain/sos/dto/response/ConnectSseResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/service/SosService.java
  src/main/java/com/TwoSeaU/BaData/global/sse/SseService.java
Labels: 🐞 BugFix

#388 Feat: [BADA-364] 알림 비동기 처리
  src/main/java/com/TwoSeaU/BaData/domain/rental/event/RentalListenerEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReStockRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RestockDeleteTargetingService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/event/ReportListenerEvent.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ReportNotificationService.java
  src/main/java/com/TwoSeaU/BaData/global/config/SpringAsyncConfig.java
Labels: ✨ Feature

#390 Test: [BADA-208] 사용자 테스트 코드 작성
  src/test/java/com/TwoSeaU/BaData/domain/user/service/UserServiceTest.java
Labels: ✅ Test

#391 Test: [BADA-357] 결제 테스트코드 작성
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/GetMerchantUidRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/enums/PaymentStatus.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/test/java/com/TwoSeaU/BaData/domain/trade/service/PaymentServiceTest.java
Labels: ✅ Test

#396 Fix: [BADA-376] imageURL 반환 제거
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/PostResponse.java
Labels: 🐞 BugFix

#398 Feat: [BADA-377] 게시물 찜 response에 MobileCarrier 추가
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetLikesPostResponse.java
Labels: ✨ Feature

#399 Perf: [BADA-368] 추천 고도화
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/MockController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/RecommendController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PostVector.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/JdbcRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostSearchService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostVectorizer.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/RecommendService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/UserProfileVectorizer.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/VectorUtils.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/GlobalRecommendService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/doubleVector/PostVectorizerDouble.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/doubleVector/RecommendServiceDouble.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/doubleVector/UserProfileVectorizerDouble.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/doubleVector/VectorUtilsDouble.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/floatVector/PostVectorizerFloat.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/floatVector/RecommendServiceFloat.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/floatVector/UserProfileVectorizerFloat.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/floatVector/VectorUtilsFloat.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/pgVector/RecommendServicePg.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/pgVector/UserProfileVectorizerPg.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/recommend/pgVector/VectorUtilsPg.java
  src/test/java/com/TwoSeaU/BaData/domain/trade/service/PostServiceTest.java
  src/test/java/com/TwoSeaU/BaData/domain/user/service/UserServiceTest.java
Labels: ⚡️performance

#401 Test: [BADA-382] 목데이터 생성
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✅ Test
