Repository Ureca-Final-Project-Team2/be_badata, pull requests merged in 2025-07, with the labels that each got.

#28 Setting: [BADA-66] 공통 코드 설계
  .gitignore
  build.gradle
  src/main/java/com/TwoSeaU/BaData/BaDataApplication.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
  src/main/java/com/TwoSeaU/BaData/domain/user/exception/UserException.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserRepository.java
  src/main/java/com/TwoSeaU/BaData/global/common/BaseEntity.java
  src/main/java/com/TwoSeaU/BaData/global/exception/GlobalException.java
  src/main/java/com/TwoSeaU/BaData/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/TwoSeaU/BaData/global/response/ApiResponse.java
  src/main/java/com/TwoSeaU/BaData/global/response/BaseException.java
  src/main/java/com/TwoSeaU/BaData/global/response/GeneralException.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#30 [BADA-51] 거래 엔티티 생성
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Data.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/GifticonCategory.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/MobileCarrier.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Partner.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PayMethod.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PaymentStatus.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PostLikes.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Report.java
Labels: ✨ Feature

#32 Feat: [BADA-68] 소셜 로그인 + Redis,WebClient,Swagger 세팅
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/auth/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/AuthController.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/swagger/AuthApi.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/kakao/request/GetKakaoUserProfileRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/kakao/request/KakaoAccount.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/kakao/request/KakaoProfile.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/kakao/request/KakaoProperties.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/request/GetOAuth2UserProfileRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/oauth2/request/GetSocialLoginTokenRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/response/CheckNewUserResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/response/IssueServiceTokenResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/response/IssueTokenUserStatusResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/exception/AuthException.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/JwtFilter.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/ServiceTokenProvider.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/handler/JwtAuthenticationEntryPointHandler.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/AuthService.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/KakaoLoginApiProcessor.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/SocialLoginApiProcessor.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/SocialLoginApiProcessorSelector.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/SocialUserService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/Role.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/SocialType.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserRepository.java
  src/main/java/com/TwoSeaU/BaData/global/config/SwaggerConfig.java
  src/main/java/com/TwoSeaU/BaData/global/config/WebClientConfig.java
  src/main/java/com/TwoSeaU/BaData/global/exception/GlobalException.java
  src/main/java/com/TwoSeaU/BaData/global/redis/RedisConfig.java
  src/main/java/com/TwoSeaU/BaData/global/redis/RedisUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#33 Feat: [BADA-50] 사용자 관련 entity 생성
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/CoinHistory.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/SearchHistory.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/UserLikes.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/CoinSource.java
Labels: ✨ Feature

#37 Feat: [BADA-70] 게시글 조회 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/TradeController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/PostResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/PostsResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/UserPostsResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Data.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PostCategory.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/DataRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/GifticonRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#43 Feat: [BADA-80] 토큰 재발행
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/AuthController.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/swagger/AuthApi.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/dto/response/CheckNewUserResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/exception/AuthException.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/JwtFilter.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/AuthService.java
Labels: ✨ Feature

#44 Feat: [BADA-83] 찜, 신고 기능 추가
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/LikeController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/ReportController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/DeletePostLikesResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/SavePostLikesResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/SaveReportResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/PostLikes.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Report.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/LikeService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ReportService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/exception/UserException.java
Labels: ✨ Feature

#45 Feat: [BADA-79] SOS 관련 엔티티 생성
  src/main/java/com/TwoSeaU/BaData/domain/sos/entity/Sos.java
Labels: ✨ Feature

#47 Feat: [BADA-49] 렌탈 관련 엔티티 생성
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/DeviceReservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/QuickReply.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Review.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/ReviewQuickReply.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/enums/ReservationStatus.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/QuickReplyRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewQuickReplyRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/Device.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/ReStock.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/Store.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/StoreDevice.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/StoreLikes.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/DeviceRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/ReStockRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/CoinHistory.java
  src/main/resources/application.yml
Labels: ✨ Feature

#54 Feat: [BADA-86] 사용자 데이터량 조회 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/SocialUserService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/DataResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#57 Feat: [BADA-98] Cors 관련 설정 세팅 exposedHeader 추가
  src/main/java/com/TwoSeaU/BaData/global/config/WebConfig.java
Labels: 🔨 Refactor

#58 Feat: [BADA-95] 사용자 코인 조회 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/auth/service/SocialUserService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/CoinResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#65 Fix: [BADA-96] push 시 CI 비활성화 적용
  .github/workflows/ci.yml
Labels: 🐞 BugFix

#69 Feat: [BADA-103] refreshToken 만료시 401 처리
  src/main/java/com/TwoSeaU/BaData/domain/auth/exception/AuthException.java
Labels: ✨ Feature

#72 Feat: [BADA-93] 게시글 등록 API
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveGifticonPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/SavePostResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Data.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/GifticonCategoryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#75 Feat: [BADA-108] 사용자 구매 내역 조회 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PaymentRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PostLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetAllPurchasesResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetPurchaseResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#85 Feat: [BADA-114] 게시글 상세 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetDataDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetGifticonDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetPostDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetSellerResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#87 Feat: [BADA-117] 거래글 수정, 삭제 API
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdatePostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/DeletePostResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#88 Feat: [BADA-116] 가맹점 상세 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/store/controller/StoreController.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/projection/StoreWithDistanceProjection.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/StoreResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/StoreWithDistanceProjection.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/service/StoreService.java
Labels: ✨ Feature

#93 Feat: [BADA-116] 기기 예약에 필요한 장치 정보 조회 API, 기기 예약 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/RentalController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/projection/AvailableDeviceProjection.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/request/ReserveDeviceRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/request/ReserveRentalRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReservationDeviceInfoResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/DeviceReservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/store/exception/StoreException.java
Labels: ✨ Feature

#98 Feat: [BADA-122] 예약 취소 및 찜 API 구현
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/RentalController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/store/controller/StoreLikeController.java
  src/main/java/com/TwoSeaU/BaData/domain/store/exception/StoreException.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/service/StoreLikeService.java
Labels: ✨ Feature

#99 Feat: [BADA-120] 제휴사 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PartnerController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetPartnerResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Partner.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PartnerRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PartnerService.java
Labels: ✨ Feature

#104 Fix: [BADA-129] commnent 오탈자 수정
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveDataPostRequest.java
Labels: 🐞 BugFix

#102 Feat: [BADA-127] 재입고 알림 저장 API
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/RestockController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/request/RestockDeviceRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/ReStock.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReStockRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RestockService.java
Labels: ✨ Feature

#109 Refactor: [BADA-131] 필요없는 swagger 부분 삭제
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/AuthController.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/controller/swagger/AuthApi.java
Labels: ✨ Feature

#118 Feat: [bada 125] 결제 API 구현
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/ServiceTokenProvider.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/config/IamportConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PaymentController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/CreatePaymentResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetValidatePaymentResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PaymentRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
Labels: ✨ Feature

#120 Fix: [BADA-139] env 추가에 따른 수정 적용
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ⚙ Setting

#122 Feat: [BADA-132] SOS 요청 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/sos/repository/SosQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/repository/SosQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/repository/SosRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetSosResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#133 Feat: [BADA-148] 예약과 가맹점 사이 연관관계 세팅
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/request/ReserveRentalRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Review.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
Labels: 🔨 Refactor

#132 Feat: [BADA-149] 사용자 팔로워, 팔로잉 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetFollowsResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/UserLikes.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/FollowType.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserLikesQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserLikesQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#136 Feat: [bada 151] 검색 기록 저장
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/SearchHistoryRepository.java
Labels: ✨ Feature

#144 Refactor: [BADA-148] 리뷰 생성 및 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/RentalController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/ReviewController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/request/CreateReviewRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowRentalResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReservedDeviceResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReviewResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReviewWithMetaResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Review.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewCustomRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
  src/main/java/com/TwoSeaU/BaData/domain/store/entity/Store.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepositoryImpl.java
Labels: ✨ Feature

#146 Feat: [BADA-157] 유효성 검사 추가 #145
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdatePostRequest.java
Labels: ✨ Feature

#148 Refactor: [BADA-158] cors 에러 해결 위한 origin 세팅
  src/main/java/com/TwoSeaU/BaData/global/config/WebConfig.java
Labels: 🔨 Refactor

#152 Feat: [BADA-160] S3 세팅
  build.gradle
  src/main/java/com/TwoSeaU/BaData/global/config/S3Config.java
  src/main/java/com/TwoSeaU/BaData/global/exception/GlobalException.java
  src/main/java/com/TwoSeaU/BaData/global/s3/S3ImageService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#157 Feat: [BADA-167] 거래 커뮤니티 이미지 저장/삭제
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#159 Feat: [BADA-170] 이슈 템플릿 추가 생성
  .github/ISSUE_TEMPLATE/test-request-form.yml
Labels: ⚙ Setting

#161 Feat: [BADA-171] 리뷰 메타 데이터 및 리스트 반환 정보 수정
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/ReviewController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowCountPerQuickReplyResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReviewMetaResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReviewResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewQuickReplyRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
Labels: ✨ Feature

#163 Feat: [BADA-173] 주소 생성, 조회, 삭제
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/AddressController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/request/AddressCreateRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetAddressResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetAddressSliceResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/Address.java
  src/main/java/com/TwoSeaU/BaData/domain/user/exception/UserException.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/AddressRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/AddressService.java
Labels: ✨ Feature

#166 Feat: [BADA-166] 사용자 공유기 대여 내역 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetRentalResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#170 Fix: [BADA-182] 테스트를 위한 Exception 민감도 약화
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/ELAResult.java
Labels: 🔨 Refactor

#172 Feat: [BADA-183] 예약 가격 계산 및 저장 #169
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/Reservation.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
Labels: ✨ Feature

#173 Fix: [BADA-184] 데이터 게시글 이미지 미필요에 따른 file 삭제
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: 🔨 Refactor

#179 Setting: [BADA-189] 고도화 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/performance-request-form.yml
Labels: ⚙ Setting

#187 Test: [BADA-190] 테스트용 API 개발
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/ELAResult.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/ELAService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#195 Feat: [BADA-196] 거래 게시글 업로드 시 OCR 적용 API 구현
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/OCRController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/OCRService.java
Labels: ✨ Feature

#201 Feat: [BADA-205] 유저 팔로우/언팔로우 기능
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/CreateFollowResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/exception/UserException.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/UserLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#204 Test: [BADA-210] 테스트 코드 관련 초기 세팅
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/request/StoreMapSearchRequest.java
  src/test/java/com/TwoSeaU/BaData/domain/store/repository/StoreRepositoryTest.java
  src/test/java/com/TwoSeaU/BaData/domain/store/service/StoreServiceTest.java
Labels: ✅ Test

#206 Refactor: [BADA-211] Device 반환 시 가격과 함께 반환
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowDeviceInfoResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreDeviceWithRemainCountResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepositoryImpl.java
Labels: 🔨 Refactor

#211 Feat: [BADA-215] 토큰 만료 시 특정 코드 발급
  src/main/java/com/TwoSeaU/BaData/domain/auth/exception/AuthException.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/JwtFilter.java
  src/main/java/com/TwoSeaU/BaData/domain/auth/jwt/ServiceTokenProvider.java
Labels: ✨ Feature

#214 Feat: [BADA-221] 가맹점 상세 정보 조회 시 이름과 함께 반환
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreDetailResponse.java
Labels: ✨ Feature

#218 Setting: [BADA-226] CICD 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ✨ Feature

#223 Feat: [BADA-228] OCR 결과 response
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetImageUploadResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#229 Feat: [BADA-231] OCR 응답값으로 제휴처 추가
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/OCRResult.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetImageUploadResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/OCRService.java
Labels: ✨ Feature

#232 Fix: [BADA-234] env 수정 #230
  .github/workflows/cd.yml
Labels: 🐞 BugFix

#234 Test: [BADA-235] CICD 테스트
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/ReportController.java
Labels: ✅ Test

#236 Feat: [BADA-233] 거래 커뮤니티 수정사항 반영
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PaymentController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PostController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveGifticonPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdateDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdateGifticonPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetGifticonDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PaymentRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/LikeService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PostService.java
Labels: ✨ Feature

#239 Feat: [BADA-236] 기프티콘 유효기간 검증 기능
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/OCRService.java
Labels: ✨ Feature

#241 Refactor: [BADA-238] 렌탈 관련 API 응답 수정
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/projection/AvailableDeviceProjection.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReservationDeviceInfoResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/controller/StoreController.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreLikesRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/service/StoreService.java
Labels: ✨ Feature, 🔨 Refactor

#244 Feat: [BADA-243] 신고 내역 조회 시 이미지와 타이틀 반환 추가
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetReportResponse.java
Labels: ✨ Feature

#246 Feat: [BADA-240] 예약 취소로 인한 재입고 시 알림 전송
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/alarm/AlarmController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/entity/ReStock.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReStockRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RestockNotificationService.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RestockService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/FcmToken.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/FcmTokenRepository.java
  src/main/java/com/TwoSeaU/BaData/global/fcm/FCMService.java
  src/main/java/com/TwoSeaU/BaData/global/fcm/dto/NotificationRequest.java
Labels: ✨ Feature

#248 Feat: [BADA-248] 렌탈 대여 기간 지정 안할 시 전체 갯수 반환
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/RentalController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/DeviceReservationRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
Labels: ✨ Feature

#254 Feat: [BADA-253] 거래 커뮤니티 변경/추가사항 반영
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/PaymentController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/GetMerchantUidRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/SaveGifticonPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdateDataPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/request/UpdateGifticonPostRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetDataDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetGifticonDetailResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/PostResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Data.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Gifticon.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Post.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetLikesPostResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetPurchaseResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetSaleResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/CoinSource.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/CoinHistoryRepository.java
Labels: ✨ Feature

#261 Feat: [BADA-256] 리뷰 작성을 위한 응답 중 방문 횟수 함께 반환
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowRentalResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
Labels: ✨ Feature, 🐞 BugFix

#265 Feat: [BADA-262] 가맹점 리스트 반환 시 가맹점 사진과 함께 반환
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreResponse.java
Labels: ✨ Feature

#255 Feat: [BADA-252] 코인 내역 조회 시 상세 내역 추가
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetCoinHistoryResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/CoinHistory.java
  src/main/java/com/TwoSeaU/BaData/domain/user/enums/CoinSource.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/CoinHistoryQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/CoinHistoryQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/CoinHistoryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#269 Fix: [BADA-265] 쿼리 오류 수정
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/MockController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/GetTrendingResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/PaymentRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/MockService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
Labels: 🐞 BugFix

#271 Feat: [BADA-269] 요금제 데이터 엔티티 생성
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/PlanData.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/PlanDataRepository.java
Labels: ✨ Feature

#281 Setting: [BADA-276] 프로메테우스, 그라파나 세팅
  build.gradle
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#279 Feat: [BADA-274] 주소 엔티티 변경 및 주소 응답 DTO 변경
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowRentalResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/RentalService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/request/AddressCreateRequest.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetAddressResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/Address.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/AddressService.java
Labels: ✨ Feature

#286 Feat: [BADA-278] 사용자 데이터 조회 시 사용자명/요금제명/전체 데이터량 값 추가
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/DataResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetDataResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#290 Feat: [BADA-280] 사용자 정보 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetUserInfoResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#291 Feat: [BADA-281] 리뷰 응답 시 포인트 획득 및 예약 장치 DTO 수정
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowRentalResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/exception/RentalException.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/User.java
Labels: ✨ Feature

#296 Feat: [BADA-291] SSH 터널링 과정 추가
  .github/workflows/cd.yml
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/TrendingService.java
Labels: ✨ Feature

#297 Fix: [BADA-291] CD 오류 해결 #295
  .github/workflows/cd.yml
Labels: ✨ Feature

#299 Fix: [BADA-292] CD 오류 해결
  .github/workflows/cd.yml
Labels: ✨ Feature

#301 Fix: [BADA-293] CD 오류 해결
  .github/workflows/cd.yml
Labels: ✨ Feature

#302 Feat: [BADA-288] 사용자 신고 관련 조회 API 수정
  src/main/java/com/TwoSeaU/BaData/domain/trade/entity/Payment.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/exception/TradeException.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportQueryRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/repository/ReportRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/user/controller/UserController.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetReportInfoResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetReportResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetTotalReportCountResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/service/UserService.java
Labels: ✨ Feature

#304 Feat: [BADA-294] CORS URL 추가
  src/main/java/com/TwoSeaU/BaData/global/config/WebConfig.java
Labels: ✨ Feature

#306 Feat: [BADA-295] 사용자 코인 내역 조회 시 전체코인량 수정
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetCoinHistoryResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/user/entity/CoinHistory.java
  src/main/java/com/TwoSeaU/BaData/domain/user/repository/CoinHistoryQueryRepositoryImpl.java
Labels: ✨ Feature

#311 Feat: [BADA-304] 리뷰 단일 조회 API
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/controller/ReviewController.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/dto/response/ShowReviewOneResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/rental/service/ReviewService.java
Labels: ✨ Feature

#314 Feat: [BADA-306] 재입고 조회 시 매장명, 위치, 남은 재고 개수, 대여 개수 추가
  src/main/java/com/TwoSeaU/BaData/domain/rental/repository/ReStockQueryRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/user/dto/response/GetRestockResponse.java
Labels: ✨ Feature

#315 Feat: [BADA-305] 지도 클러스터링 적용
  src/main/java/com/TwoSeaU/BaData/domain/store/controller/StoreController.java
  src/main/java/com/TwoSeaU/BaData/domain/store/dto/response/ShowStoreMapResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepository.java
  src/main/java/com/TwoSeaU/BaData/domain/store/repository/StoreDeviceCustomRepositoryImpl.java
  src/main/java/com/TwoSeaU/BaData/domain/store/service/StoreService.java
  src/test/java/com/TwoSeaU/BaData/domain/store/controller/StoreControllerTest.java
  src/test/java/com/TwoSeaU/BaData/domain/store/service/StoreServiceTest.java
Labels: ✨ Feature

#331 Feat: [BADA-323] 홈 기능 추가 API 개발
  src/main/java/com/TwoSeaU/BaData/domain/trade/controller/RecommendController.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/dto/response/SaveRecommendLikesResponse.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/PaymentService.java
  src/main/java/com/TwoSeaU/BaData/domain/trade/service/RecommendService.java
Labels: ✨ Feature

#333 Feature/bada 324 delete sos token
  src/main/java/com/TwoSeaU/BaData/domain/auth/config/SecurityConfig.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/controller/SosController.java
Labels: ✨ Feature

#339 Feat: [BADA-328] SOS 요청 시 SSE 기능 구현
  src/main/java/com/TwoSeaU/BaData/domain/sos/controller/NotificationController.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/controller/SosController.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/exception/SosException.java
  src/main/java/com/TwoSeaU/BaData/domain/sos/service/SosService.java
  src/main/java/com/TwoSeaU/BaData/global/sse/SseService.java
Labels: ✨ Feature
